### ISSUE TITLE
How to speed up loading of charts and close to what it takes on tradingview website ?

### ISSUE THREAD

**Issue by dgurudot** [SuperPenguin/charting-library-flutter#3]
It takes several seconds to probably start the server and load up charts. I am trying to see what could be optimized to make it faster and close to what we experience on tradingview website.

Can you please suggest or update code for faster chart load time? I could possibly think of keeping the server started in advance. 

Kindly share possible solutions.

**Comment by dgurudot** [comment]
I am also wondering if the following package can be possibly used without running an in-app localhost server.

https://pub.dev/packages/webview_flutter_plus

I am finding that once app goes into background mode and when I resume then start and stop of server may be needed because charts are not loading during resume of app from background.

**Comment by SuperPenguin** [comment]
> It takes several seconds to probably start the server and load up charts. I am trying to see what could be optimized to make it faster and close to what we experience on tradingview website.
> 
> Can you please suggest or update code for faster chart load time? I could possibly think of keeping the server started in advance.
> 
> Kindly share possible solutions.

There is no way to improve it atm, even with official webview, loading a empty page still take time, this also not including the tv lib actually loading their own asset. If you use the widget on a ListView or TabBody, try using keep `keepAlive` on widget to keep the widget alive even it got out of view. The widget will stay alive as long as ListView/Tab still alive.
https://stackoverflow.com/a/62794121/14905257

> I am also wondering if the following package can be possibly used without running an in-app localhost server.
> 
> https://pub.dev/packages/webview_flutter_plus
> 
> I am finding that once app goes into background mode and when I resume then start and stop of server may be needed because charts are not loading during resume of app from background.

With that package I really doubt it will, because the tv lib load the their asset with network request, not by simple html tag like `<script src='./something'>`.

Another option is to serve the webpages from a server, then change the WebView url and remove all localhost references. This will no doubt increase the load time. 

https://github.com/SuperPenguin/charting-library-flutter/blob/b25c948f06f9176b3af0bf9791a044b14dff7df9/flutter_app/lib/components/tvchart/tvchart.dart#L267

```
url: Uri.parse('https://mydomain.com/path-to-chart'),
```

**Comment by SuperPenguin** [comment]
> I am finding that once app goes into background mode and when I resume then start and stop of server may be needed because charts are not loading during resume of app from background.

Localhost issue fixed on 616671938fa42c138a4334576c66b33e4b011195
