### ISSUE TITLE
[Query] If I'm trying to subscribeBars what should be the return value of that function

### ISSUE THREAD

**Issue by imvab** [SuperPenguin/charting-library-flutter#6]
I'm trying to hook up the chart with live data. How and what should I return to subscribeBars function?

**Comment by SuperPenguin** [comment]
> I'm trying to hook up the chart with live data. How and what should I return to subscribeBars function?

Return nothing, because callHandler is not used for returning value on stream/async multiple times.

The code in chart project is actually a mistake, it should not calling onTick on Promise.

In this case when subscribeBars happen it should follow flow like so

```
[JS -> Dart] subscribeBars with listenerGuid
[Dart] handling request and pooling data
[Dart -> JS] evaluateJavascript pass listenerGuid with Bar (may happen on stream/async multiple times)
[JS -> Dart] unsubscribeBars with listenerGuid
[Dart] handling disposing request
```

You will need to save listenerGuid and onTick in map on JS side and listenerGuid and symbolInfo in map on dart side so that when dart can dispose properly on dispose and know which bar data should it pass then JS can call correct onTick callback.

**Comment by imvab** [comment]
Hi @SuperPenguin 
Thanks for the reply however I'm not able to completely understand the flow. Any chance you could share a small snippet or gist on how this would go about?

**Comment by SuperPenguin** [comment]
> Hi @SuperPenguin
> Thanks for the reply however I'm not able to completely understand the flow. Any chance you could share a small snippet or gist on how this would go about?

c40735776f43db8ed5b26b54bba338d7ff46498c
