### ISSUE TITLE
Some miscellaneous issues

### ISSUE THREAD

**Issue by dgurudot** [SuperPenguin/charting-library-flutter#8]
We recently did the integration of live data feed as well using your latest guidance and code commit.
Based on our overall testing, there are four specific issues:

1. Volume - It is not showing although we are passing OHLCV for candles. It does show up on the bottom but not next to the price.
2. % change and $$ change. It is showing value from the last candle but not the close price on that day. 
3. Charts stop updating mid-day and show market closed. We have set the timezone accurately and it does show accurate value on the chart but three hours after the market opens, it says the market is closed and we are puzzled what parameter is changing that status.
4. Occasionally, charts are blank after some activity or inactivity on the app.

**Comment by SuperPenguin** [comment]
1, 2, 3 is more related to charting_library instead of implementation. You should ask there or check the manual if you want to change the configuration, this repo example doesn't modify the config that much and use default configuration as much as possible.

> 1. Volume - It is not showing although we are passing OHLCV for candles. It does show up on the bottom but not next to the price.
> 2. % change and $$ change. It is showing value from the last candle but not the close price on that day.

It's visible on crosshair hover, if you meant is label on price scale you should ask on charting library or check the manual, cause I also have no idea to enable those.
<img src="https://user-images.githubusercontent.com/1574722/131435439-5e6a69a7-791e-4d6e-81e7-c6fe16abd761.png" alt="screenshot-android" width="360" height="800">

> 3. Charts stop updating mid-day and show market closed. We have set the timezone accurately and it does show accurate value on the chart but three hours after the market opens, it says the market is closed and we are puzzled what parameter is changing that status.

Check your session to match with your exchange session, this repo example here use session for Indonesian Stock Exchange. 0900-1130,1330-1500. TradingView has parser for testing here http://tradingview.github.io/checksession.html

> 4. Occasionally, charts are blank after some activity or inactivity on the app.

You need to debug both WebView and flutter app to find any error and post the stacktrace here, at the moment the current example is used in live app and working fine even app is thrown to background for prolonged time.

In case your chart is blank after got redirected to TradingView by pressing TradingView logo and pressing back to chart fast enough, there is actually issue with that, and atm is not fixable.
https://github.com/SuperPenguin/charting-library-flutter/blob/c40735776f43db8ed5b26b54bba338d7ff46498c/flutter_app/lib/components/tvchart/tvchart.dart#L287-L291
